spring:
  application:
    name: taskmanagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jwt:
    secret-key: "Thay_Bang_Mot_Chuoi_That_Dai_Tren_32_Ky_Tu_Nhe_An"
    expiration: 86400000 # 24 gio tinh bang miliseconds
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080